apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-user-service
  template:
    metadata:
      labels:
        app: db-user-service
    spec:
      containers:
      - name: mongodb
        image: mongo:latest  # MongoDB image (latest version)
        ports:
        - containerPort: 27017  # MongoDB default port
        env:
        - name: MONGO_INITDB_DATABASE
          value: "User"  
---
apiVersion: v1
kind: Service
metadata:
  name: db-user-service
spec:
  selector:
    app: db-user-service
  ports:
    - protocol: TCP
      port: 27017  # MongoDB default port
      targetPort: 27017  # MongoDB default port
